import React,{useState} from 'react';
import {Box,Check,ArrowUpRight,Palette,Image} from 'lucide-react';
import {useStudio} from './StudioContext';
import {Button} from '../components/ui/button';
import {toast} from 'sonner';

export default function BrandPage(){
  const {brand,setBrand,save,saving,setPresentation}=useStudio();const [logoError,setLogoError]=useState(false);
  const change=(key,value)=>{setBrand({...brand,[key]:value});if(key==='logo_url')setLogoError(false);};
  return <main className="document-page brand-page" data-testid="branding-page"><div className="document-heading"><div><span className="overline">MAKE THE STUDIO YOUR OWN</span><h1 data-testid="branding-heading">Your collection.<br/><span>Your signature.</span></h1></div><span className="edition-badge" data-testid="branding-edition">PITCH EDITION / 01</span></div><div className="brand-columns"><section className="brand-form"><h2>Studio identity</h2><label className="field-label" htmlFor="brand-name">Brand name<input id="brand-name" data-testid="brand-name" maxLength={60} value={brand.name} onChange={e=>change('name',e.target.value)}/></label><label className="field-label" htmlFor="brand-subtitle">Collection / subtitle<input id="brand-subtitle" data-testid="brand-subtitle" maxLength={60} value={brand.subtitle} onChange={e=>change('subtitle',e.target.value)}/></label><label className="field-label" htmlFor="brand-logo">Logo URL · HTTPS<input id="brand-logo" data-testid="brand-logo" type="url" placeholder="https://your-brand.com/logo.png" maxLength={2000} value={brand.logo_url} onChange={e=>change('logo_url',e.target.value)}/></label>{brand.logo_url&&!brand.logo_url.startsWith('https://')&&<p className="error-message" data-testid="brand-logo-validation">Use an HTTPS image address.</p>}
    <h2>Signature color</h2><div className="brand-swatches">{['#dca55e','#94b6a0','#b1bbcf','#df9a8c','#b9b799'].map(color=><button key={color} data-testid={`brand-color-${color.slice(1)}`} aria-label={`Accent ${color}`} style={{background:color}} onClick={()=>change('accent',color)}>{color===brand.accent&&<Check size={20}/>}</button>)}<input type="color" data-testid="brand-custom-color" aria-label="Custom accent color" value={brand.accent} onChange={e=>change('accent',e.target.value)}/></div><div className="brand-actions"><Button className="accent-button" data-testid="save-brand-button" disabled={saving||!brand.name.trim()||(brand.logo_url&&!brand.logo_url.startsWith('https://'))} onClick={save}><Check size={15}/>{saving?'Saving…':'Save identity'}</Button></div></section><section className="brand-preview"><div className="overline">LIVE IDENTITY PREVIEW</div><div className="brand-preview-logo" style={{color:brand.accent}}>{brand.logo_url?.startsWith('https://')&&!logoError?<img src={brand.logo_url} alt="Brand logo preview" data-testid="brand-logo-preview" onError={()=>setLogoError(true)}/>:<Box size={58} strokeWidth={1}/>}</div>{logoError&&<p className="error-message" data-testid="brand-logo-error">Logo image could not be loaded.</p>}<h2 data-testid="brand-preview-name">{brand.name||'Your studio'}</h2><p data-testid="brand-preview-subtitle">{brand.subtitle}</p><div className="brand-preview-line"/><div className="preview-edition">THE ATELIER KITCHEN<span>COLLECTION 01</span></div></section></div></main>;
}