import React,{useState} from 'react';
import {Download,ArrowUpRight,FileText,Check,Package,Settings2} from 'lucide-react';
import {useStudio} from './StudioContext';
import {money as formatMoney,formatDimension} from './engine';
import {Button} from '../components/ui/button';
import {Toggle} from './Controls';
import {toast} from 'sonner';
const money=value=>formatMoney(value,2);

export default function QuotePage(){
  const {scene,config,update,busy}=useStudio();const [filter,setFilter]=useState('all');
  const q=scene.quote,prices=config.quote.show_prices;
  const lines=q.lines.filter(l=>filter==='all'||l.category===filter);
  const setting=(k,v)=>update({quote:{...config.quote,[k]:v}});
  const download=()=>{
    const rows=[['Component','Category','Quantity',...(prices?['Unit price USD','Total USD']:[])],...q.lines.map(l=>[l.name,l.category,l.quantity,...(prices?[l.unit_price,l.total]:[])]),...(prices?[["Finishing","service",1,q.finishing,q.finishing],["Assembly labor","service",1,q.labor,q.labor],["ILLUSTRATIVE TOTAL — NOT A BINDING QUOTE","",'', '',q.total]]:[])];
    const blob=new Blob([rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8;'});
    const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='atelier-kitchen-bom.csv';a.click();URL.revokeObjectURL(url);toast.success('Bill of materials downloaded');
  };
  return <main className="document-page quote-page" data-testid="quote-page"><div className="document-heading"><div><span className="overline">THE ATELIER KITCHEN / PROJECT 01</span><h1 data-testid="quote-heading">A considered design.<br/><span>Every detail accounted for.</span></h1></div><Button className="accent-button" data-testid="download-bom-button" onClick={download} disabled={busy}><Download size={15}/>Download BOM</Button></div>
    <div className="quote-summary-strip"><div><span>CONFIGURED CABINETS</span><strong data-testid="quote-cabinet-count">{String(scene.cabinets.length).padStart(2,'0')}</strong></div><div><span>INDIVIDUAL COMPONENTS</span><strong data-testid="quote-parts-count">{Object.values(scene.counts).reduce((a,b)=>a+b,0)}</strong></div><div><span>LOGICAL RUN LENGTH</span><strong data-testid="quote-run-length">{formatDimension(scene.dimensions.run_length,config.units)}</strong></div><div><span>{prices?'ILLUSTRATIVE ESTIMATE':'WALL FOOTPRINT'}</span><strong className="accent-text" data-testid="bom-total-quote-readout">{prices?money(q.total):`${formatDimension(scene.dimensions.footprint_width,config.units)} × ${formatDimension(scene.dimensions.footprint_depth,config.units)}`}</strong></div></div>
    <div className="quote-columns"><section className="bom-section"><div className="table-heading"><h2>Bill of materials</h2><span data-testid="bom-line-count">{q.lines.length} line items</span></div><div className="filter-tabs">{[['all','All components'],['panel','Panels'],['hardware','Hardware'],['fastener','Fasteners'],['surface','Surfaces']].map(([key,label])=><button key={key} className={filter===key?'active':''} data-testid={`bom-filter-${key}`} onClick={()=>setFilter(key)}>{label}</button>)}</div><div className="bom-table"><table data-testid="bom-table"><thead><tr><th>Component</th><th>Qty</th>{prices&&<><th>Unit</th><th>Total</th></>}</tr></thead><tbody>{lines.map(l=><tr key={l.key} data-testid={`bom-line-${l.key}`}><td><strong>{l.name}</strong><small>{l.category}</small></td><td>{l.quantity}</td>{prices&&<><td>{money(l.unit_price)}</td><td>{money(l.total)}</td></>}</tr>)}</tbody></table>{!lines.length&&<p className="empty-state" data-testid="bom-empty-state">No components in this category.</p>}</div></section>
      <aside className="quote-settings"><div className="table-heading"><h2>Quote settings</h2><Settings2 size={17}/></div><Toggle id="quote-show-prices" label="Show pricing" checked={prices} onChange={v=>setting('show_prices',v)}/><Toggle id="quote-include-hardware" label="Include hardware" checked={config.quote.include_hardware} onChange={v=>setting('include_hardware',v)}/><Toggle id="quote-include-finish" label="Include finishing" checked={config.quote.include_finish} onChange={v=>setting('include_finish',v)}/><Toggle id="quote-include-labor" label="Include assembly labor" checked={config.quote.include_labor} onChange={v=>setting('include_labor',v)}/>{config.quote.include_labor&&<label className="field-label" htmlFor="labor-rate">Hourly labor rate · USD<input id="labor-rate" data-testid="labor-rate" type="number" min="0" max="1000" value={config.quote.labor_rate} onChange={e=>setting('labor_rate',Math.min(1000,Math.max(0,Number(e.target.value))))}/></label>}
      {prices&&<div className="price-breakdown" data-testid="quote-price-breakdown"><div><span>Materials & components</span><strong>{money(q.subtotal)}</strong></div><div><span>Finishing</span><strong>{money(q.finishing)}</strong></div><div><span>Assembly labor</span><strong>{money(q.labor)}</strong></div><div className="quote-total"><span>Project estimate</span><strong>{money(q.total)}</strong></div></div>}<div className="quote-disclaimer" data-testid="pricing-disclaimer"><FileText size={18}/><p>Illustrative base-cabinet pricing only, including selected surfaces and pot racks. Not a manufacturer quote. Upper cabinets, appliances, styling items, taxes, installation and delivery are excluded.</p></div></aside></div>
  </main>;
}