import React,{useEffect,useState} from 'react';
import {NavLink,useLocation,useNavigate} from 'react-router-dom';
import {Box,Layers,LayoutTemplate,FileText,Palette,Settings2,RotateCcw,ChevronDown,ArrowUpRight,Check,Cloud,PanelLeft,PanelRight,X,Maximize2,Sun,Grid2X2,PanelTop,ArrowLeft,Loader2,Home} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {useStudio} from './StudioContext';
import {Configurator} from './Controls';
import {Viewport} from './Viewport';
import {Inspector,AssemblyTree,ExplodeControls} from './Inspector';
import QuotePage from './QuotePage';
import BrandPage from './BrandPage';

function Header(){
  const {brand,presentation,setPresentation}=useStudio();const navigate=useNavigate();const [logoFailed,setLogoFailed]=useState(false);
  useEffect(()=>setLogoFailed(false),[brand.logo_url]);
  return <header className="studio-header"><NavLink className="brand" data-testid="brand-home-link" to="/"><span className="brand-symbol">{brand.logo_url?.startsWith('https://')&&!logoFailed?<img src={brand.logo_url} alt={brand.name} onError={()=>setLogoFailed(true)}/>:<Box size={27} strokeWidth={1.3}/>}</span><span><strong data-testid="header-brand-title">{brand.name}</strong><small data-testid="header-brand-subtitle">{brand.subtitle}</small></span></NavLink><nav className="main-navigation" data-testid="main-navigation">{[['/','Design studio'],['/assembly','Assembly'],['/quote','Quote & BOM']].map(([to,label])=><NavLink key={to} to={to} end={to==='/'} data-testid={`nav-${to==='/'?'studio':to.slice(1)}`}>{label}</NavLink>)}</nav><div className="header-actions"><span className="workspace-status" data-testid="workspace-status"><span/>Demo workspace</span><button className="pitch-button" data-testid="pitch-mode-button" onClick={()=>{if(!['/','/assembly'].includes(window.location.pathname))navigate('/');setPresentation(!presentation);}}>{presentation?<X size={14}/>:<Maximize2 size={14}/>}<span>{presentation?'Exit pitch':'Pitch mode'}</span></button></div></header>;
}
function ProjectBar(){
  const {config,update,save,saving,saved,presentation,setTab}=useStudio();const location=useLocation();
  return <div className="project-bar"><div className="project-breadcrumb"><span className="project-icon"><LayoutTemplate size={17}/></span><span className="breadcrumb-root">Your projects</span><span className="breadcrumb-slash">/</span><strong data-testid="project-title">The Atelier Kitchen</strong><span className="project-badge">Concept 01</span></div><div className="project-tools"><div className="units-toggle" data-testid="units-toggle">{['mm','in'].map(u=><button key={u} data-testid={`unit-${u}`} className={config.units===u?'active':''} onClick={()=>update({units:u})}>{u}</button>)}</div><button className={`icon-button ${config.ceiling?'active':''}`} title="Toggle ceiling" aria-label="Toggle ceiling" data-testid="header-ceiling-toggle" onClick={()=>update({ceiling:!config.ceiling})}><PanelTop size={17}/></button><button className={`icon-button ${config.dimensions?'active':''}`} title="Toggle dimensions" aria-label="Toggle dimensions" data-testid="header-dimensions-toggle" onClick={()=>update({dimensions:!config.dimensions})}><Grid2X2 size={16}/></button><div className="toolbar-divider"/><Button className="save-button" variant="outline" data-testid="save-design-button" onClick={save} disabled={saving}>{saving?<Loader2 className="spin" size={14}/>:saved?<Check size={14}/>:<Cloud size={14}/>}<span>{saving?'Saving…':saved?'Saved':'Save design'}</span></Button></div></div>;
}
function Rail(){
  const {tab,setTab,setMobilePanel}=useStudio();const location=useLocation();const navigate=useNavigate();const [confirm,setConfirm]=useState(false);const {reset}=useStudio();
  const goTab=t=>{setTab(t);navigate('/');setMobilePanel('config');};
  return <><aside className="tool-rail" data-testid="tool-rail"><div>{[[Palette,'cabinets','Design palette'],[LayoutTemplate,'layout','Layout'],[PanelTop,'ceiling','Ceiling & pot racks']].map(([Icon,value,label])=><button key={value} title={label} aria-label={label} data-testid={`tool-${value}`} className={location.pathname==='/'&&tab===value?'active':''} onClick={()=>goTab(value)}><Icon size={20}/></button>)}<span className="rail-divider"/><button title="Assembly explorer" aria-label="Assembly explorer" data-testid="tool-assembly" className={location.pathname==='/assembly'?'active':''} onClick={()=>navigate('/assembly')}><Layers size={20}/></button><button title="Bill of materials" aria-label="Bill of materials" data-testid="tool-quote" className={location.pathname==='/quote'?'active':''} onClick={()=>navigate('/quote')}><FileText size={19}/></button></div><div><button title="Reset kitchen" aria-label="Reset kitchen" data-testid="reset-kitchen-button" onClick={()=>setConfirm(true)}><RotateCcw size={18}/></button><button title="Studio branding" aria-label="Studio branding" data-testid="tool-branding" className={location.pathname==='/branding'?'active':''} onClick={()=>navigate('/branding')}><Settings2 size={19}/></button><span className="studio-monogram">3D</span></div></aside><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="studio-dialog" data-testid="reset-dialog"><DialogTitle>Start with a clean slate?</DialogTitle><DialogDescription>Your kitchen configuration will return to the original concept. Your brand identity stays.</DialogDescription><Button className="accent-button" data-testid="confirm-reset-button" onClick={()=>{reset();setConfirm(false);}}>Reset kitchen</Button></DialogContent></Dialog></>;
}
export default function Studio(){
  const {scene,error,retry,busy,presentation,setPresentation,mobilePanel,setMobilePanel}=useStudio();const location=useLocation();const assembly=location.pathname==='/assembly';const documentPage=['/quote','/branding'].includes(location.pathname);
  useEffect(()=>{setMobilePanel(null);},[location.pathname,setMobilePanel]);
  useEffect(()=>{const listener=e=>{if(e.key==='Escape'){setPresentation(false);setMobilePanel(null);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[setPresentation,setMobilePanel]);
  return <div className={`studio-app ${presentation?'presentation':''}`} data-testid="studio-app"><Header/><ProjectBar/>{error&&<div className="connection-error" data-testid="connection-error">{error}<button data-testid="retry-connection" onClick={retry}>Retry</button></div>}
    <div className="workspace"><Rail/>{!scene?<div className="studio-loading" data-testid="studio-loading"><Box size={38} strokeWidth={1}/><span>Preparing your studio</span><i/></div>:documentPage?(location.pathname==='/quote'?<QuotePage/>:<BrandPage/>):<>
      <aside className={`left-panel ${mobilePanel==='config'?'mobile-open':''}`}><button className="close-mobile-panel" aria-label="Close design panel" data-testid="close-config-panel" onClick={()=>setMobilePanel(null)}><X size={19}/></button>{assembly?<AssemblyTree/>:<Configurator/>}</aside>
      <div className="viewport-wrap"><Viewport assembly={assembly}/>{assembly&&<ExplodeControls/>}<div className="mobile-panel-buttons"><button data-testid="mobile-config-button" onClick={()=>setMobilePanel('config')}><PanelLeft size={16}/>{assembly?'Parts':'Customize'}</button><button data-testid="mobile-inspector-button" onClick={()=>setMobilePanel('inspector')}><PanelRight size={16}/>Inspect</button></div></div>
      <div className={`right-panel ${mobilePanel==='inspector'?'mobile-open':''}`}><button className="close-mobile-panel" aria-label="Close inspector" data-testid="close-inspector-panel" onClick={()=>setMobilePanel(null)}><X size={19}/></button><Inspector assembly={assembly}/></div>
      {mobilePanel&&<button className="mobile-panel-backdrop" aria-label="Dismiss panel" data-testid="mobile-panel-backdrop" onClick={()=>setMobilePanel(null)}/>}
    </>}</div>
    <footer className="status-bar"><span data-testid="engine-status"><i/>{busy?'Updating design':'All systems ready'}<span className="status-divider"/>PARAMETRIC ENGINE v1.0</span><span data-testid="footer-standard">ORIGINAL EURO / 32 MM COLLECTION<span className="status-divider"/>PITCH EDITION</span></footer>
  </div>;
}